# Generated by Django 5.1.4 on 2025-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='store_id',
            field=models.CharField(default='150001', max_length=100),
        ),
    ]
